steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://jd_creation/requirements.txt', '/workspace/']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'REQUIREMENTS_TXT=/workspace/requirements.txt', '-t', 'gcr.io/praxis-23-413603/myapp', '.']
