steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://bucket_jd_creation/requirements.txt', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/praxis-23-413603/myapp', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/praxis-23-413603/myapp']
images:
  - 'gcr.io/praxis-23-413603/myapp'
