steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://jd_creation/requirements.txt', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/my-docker-repo/myapp:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/my-docker-repo/myapp:latest']
images:
  - 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/my-docker-repo/myapp:latest'
